### PR TITLE
Set faction of the teenagers in Teenagers mission to "Dummy".

### PR DESCRIPTION
**Pull request by onpon4**
So police forces don't start going after you for doing the mission.

### CODE REVIEW

**Comment by PhoenixRiver** [comment]
> So police forces don't start going after you for doing the mission.
> You can view, comment on, or merge this pull request online at:

Makes sense :)

Johann

**Comment by bobbens** [comment]
Why aggressive?

**Comment by onpon4** [comment]
Because my previous assumption that police defense is defined by faction was incorrect, I'm not sure changing the faction to "Dummy" actually made a difference, now (could have just been coincidence, as far as I know).

**Comment by PhoenixRiver** [comment]
Hello,

> Because my previous assumption that police defense is defined by faction was
> incorrect, I'm not sure changing the faction to "Dummy" actually made a
> difference, now (could have just been coincidence, as far as I know).

Thinking back I didn't have this problem with this mission but did
have a problem with another where one of my shots accidentally hit
another ship...

Johann

**Comment by bobbens** [comment]
Looks good, thanks.

**Pull request merged**
